import { ParsedCriticFeedback, ParsedSourceItem } from '../types';

/**
 * Parses the structured output generated by the Critic Chain.
 * If the format diverges, provides structured fallbacks to prevent any UI breakage.
 */
export function parseCriticFeedback(rawFeedback: string): ParsedCriticFeedback {
  if (!rawFeedback || typeof rawFeedback !== 'string') {
    return {
      rawScore: undefined,
      scoreNumber: undefined,
      strengths: [],
      areasToImprove: [],
      verdict: undefined,
      rawText: rawFeedback || '',
    };
  }

  const result: ParsedCriticFeedback = {
    strengths: [],
    areasToImprove: [],
    rawText: rawFeedback,
  };

  try {
    // 1. Extract Score (e.g. "Score: 8.5/10", "Score: 9 / 10", "8/10")
    const scoreMatch = rawFeedback.match(/Score:\s*(\d+(?:\.\d+)?)\s*\/\s*10/i) || 
                       rawFeedback.match(/(\d+(?:\.\d+)?)\s*\/\s*10/i);
    if (scoreMatch && scoreMatch[1]) {
      result.rawScore = `${scoreMatch[1]}/10`;
      result.scoreNumber = parseFloat(scoreMatch[1]);
    }

    // 2. Extract Strengths section
    const strengthsMatch = rawFeedback.match(/Strengths:\s*([\s\S]*?)(?=Areas to Improve:|One line verdict:|$)/i);
    if (strengthsMatch && strengthsMatch[1]) {
      const lines = strengthsMatch[1].split('\n');
      result.strengths = lines
        .map(l => l.replace(/^[-*•✓]\s*/, '').trim())
        .filter(l => l.length > 0 && !l.toLowerCase().includes('strengths:'));
    }

    // 3. Extract Areas to Improve section
    const improveMatch = rawFeedback.match(/Areas to Improve:\s*([\s\S]*?)(?=One line verdict:|Strengths:|$)/i);
    if (improveMatch && improveMatch[1]) {
      const lines = improveMatch[1].split('\n');
      result.areasToImprove = lines
        .map(l => l.replace(/^[-*•!]\s*/, '').trim())
        .filter(l => l.length > 0 && !l.toLowerCase().includes('areas to improve:'));
    }

    // 4. Extract One line verdict section
    const verdictMatch = rawFeedback.match(/One line verdict:\s*([\s\S]*?)$/i);
    if (verdictMatch && verdictMatch[1]) {
      result.verdict = verdictMatch[1].trim();
    }
  } catch {
    // If regex parsing fails, rawText is preserved and gracefully handled
  }

  return result;
}

/**
 * Extracts structured source items from Tavily search results or text containing URLs.
 */
export function parseSearchResults(searchResultsText: string): ParsedSourceItem[] {
  if (!searchResultsText) return [];

  const items: ParsedSourceItem[] = [];

  // Match chunks formatted by tools.py: Title=...\n URL:...\n Snippets:...
  const rawBlocks = searchResultsText.split(/\n\.\.\.\.\.\n|\n-----\n/);

  for (let i = 0; i < rawBlocks.length; i++) {
    const block = rawBlocks[i].trim();
    if (!block) continue;

    const titleMatch = block.match(/Title\s*=\s*(.+?)(?=\n|$)/i);
    const urlMatch = block.match(/URL\s*:\s*(https?:\/\/[^\s\r\n]+)/i);
    const snippetMatch = block.match(/Snippets?\s*:\s*([\s\S]+)/i);

    if (urlMatch && urlMatch[1]) {
      const url = urlMatch[1].trim();
      let domain = '';
      try {
        domain = new URL(url).hostname.replace(/^www\./, '');
      } catch {
        domain = 'web source';
      }

      const title = titleMatch && titleMatch[1] ? titleMatch[1].trim() : domain;
      const snippet = snippetMatch && snippetMatch[1] ? snippetMatch[1].trim() : '';

      items.push({
        id: `source-${i}`,
        title,
        url,
        domain,
        snippet,
      });
    }
  }

  // Fallback if formatting was different: Extract all standalone HTTP URLs
  if (items.length === 0) {
    const urlRegex = /(https?:\/\/[^\s\)\"\'\,]+)/g;
    const foundUrls = Array.from(new Set(searchResultsText.match(urlRegex) || []));

    foundUrls.forEach((url, idx) => {
      try {
        const domain = new URL(url).hostname.replace(/^www\./, '');
        items.push({
          id: `fallback-source-${idx}`,
          title: `Source: ${domain}`,
          url,
          domain,
          snippet: '',
        });
      } catch {
        // Skip invalid URL strings
      }
    });
  }

  return items;
}

/**
 * Calculates estimated reading time based on 200 words per minute.
 */
export function getReadingTime(text: string): string {
  if (!text) return '0 min read';
  const words = text.trim().split(/\s+/).length;
  const minutes = Math.max(1, Math.ceil(words / 200));
  return `${minutes} min read`;
}

/**
 * Counts words in a string.
 */
export function getWordCount(text: string): number {
  if (!text) return 0;
  return text.trim().split(/\s+/).filter(Boolean).length;
}
